name: Render LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name: Move PDF to root
      run: |
        mv main.pdf $GITHUB_WORKSPACE/main.pdf
