name: latexmk
on:
  push:
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.10.9
        with:
          cmd: latexmk
          path: /
          opts: -pdf
          packages: acmart tikz
